import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { copyFile, mkdir } from "node:fs/promises";

const production = process.argv[2] === "production";

await mkdir("dist", { recursive: true });
await Promise.all([
  copyFile("manifest.json", "dist/manifest.json"),
  copyFile("styles.css", "dist/styles.css")
]);

const context = await esbuild.context({
  banner: {
    js: "/* Generated by ZJ HTML Studio. Edit TypeScript sources in src/. */"
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    ...builtinModules,
    ...builtinModules.map(moduleName => `node:${moduleName}`)
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "dist/main.js",
  platform: "node",
  sourcemap: production ? false : "inline",
  target: "es2022",
  treeShaking: true
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
